language: csharp
mono: none
dotnet: 2.1
env:
  global:
    secure: F578bJrQ5B4rf1fhKxIJ9oO9caunOvH9FzS/KmPKFXq1PMMFqzRVGFbfVQ1ZO++oP8j8+HBB+rzWaub65qqYiO4yzb3Bsk0t1u2IgWGNPk1g4+tAr5MvXzFRVSJYn1rRL+sM5SLubAxHEuhzQIk3reQC+C26KbQ03SZlhCm9uSetR07geeqVKwdWRYER/pwskmm5XAYn/XAbR17jxoOWrIWyQrtQ7MlsB/uA9Gcf03U/5XK1oQb47uW3lDSxF9n7Ewd0mNL0s3pcxZhQZB4tU2URebho+1SNonR1aODhuNmQAfkxc8g1K7tHqm3uHBOhRLPgZGoAFBmWlaM6lGOcNhBTkxYo4VfP4wkO/6ziLpwTQAOrNaQNkVejwIjgEdGr+6WDGn4bjE8mose/BQyxNTXg8jXFWaAAU74CJAG2Mjst80FKf/dWmycRecDr2iO/nixTBQa4mhyhzPUiZvtPYZyf5kk62MIKQgScJM6/Sfzkwto00xBWP8NU0EWDaMfD1kutPWoAHSivTeOHMgdYcePjF1TmEqt9bwHUHHup4hImU/Mmqlx7wX0B5n+LccnaU2Efd9+ivOzvSrgHZAmEdty0bkf33WDjcEns7NqEXLO+LSBfzzNBxZQQiNYQJ7pwuSmxRirifxGzQomn+eBZF1aCN4SNTVVQDSbPMxoRxKM=
script:
- cd src
- dotnet restore
- dotnet test Unidays.Client.Tests
- dotnet pack Unidays.Client -c Release /property:PackageVersion=1.2.$TRAVIS_BUILD_NUMBER
- cd -
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh 1.2.$TRAVIS_BUILD_NUMBER $NUGET_API_KEY
  on:
    branch: master
notifications:
  slack:
    secure: KbDCgq4hae8yGVU9jmgJLDxYGizIc6bz14wRNwBeWRJBUbNPKI7LMrbzJ7bT4G4wfoP+R4kEd9hbHkucitSZ7wmgumaGE3qOuLw2AZYYoyWRNu7pk2egp49jmHDQatULXZ/uW+dSdJ61V5CBdAQESQPL1RlZqDTySg0W2tXbyh0XsY3JzKB86Kvarul4keqgdEIrizeqmkEHbaqJw4wKSvBRfKM0jKGpg8k/8vCNi0dbsh55uQYMDEhHqs2MK+CQ6BxAIoeWWad3rTb/Pxval5Iuw/mDJf0VHnvamTuBlRj7HkoL2VU7S6509rZgVfnw4LDSNFSDGbQFSqyjkJCu0VtZI1BW6r/WdPogcFX7GZvgBKKoNIPRXCyL858oGfR2HK1k24OJIZ0D4mrHnopaHOtmHS+RKK/1G2xAuOniSESnj2Ko/Zqqla2XfHOxWqhNVKd7i6Kf+okC/ZT2DqJ9TJuu91RBovZS6sofXEdE1z29olbswb+MhiFyGGh75rgjRWXTgcnPiwmcUc73uE5BDqSGqETThVI1OFChjNWdcla0CTKD8vb9UKe+fyDjG8kkZqpaKg3afppe4pRIW6dFwk2xKTN3ChNA9i9ZwIujEw+mb3Oju//+FjttZ4FmV8LFp1Dxx7hB75YBFtZ66zGy1AWmoTStBv5+T0qgcLFxIKQ=
    on_success: never
    on_failure: always
