image: Visual Studio 2017
version: 1.0.{build}-{branch}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
configuration: Release
branches:
  only:
    - master
skip_tags: true
max_jobs: 1
init:
  - git config --global core.autocrlf true
clone_depth: 1
artifacts:
  - path: '*.nupkg'
#------ tests configuration ------#
test_script:
  - cmd: dotnet restore ./src/Unidays.Tests/Unidays.Tests.csproj --verbosity m
  - cmd: cd ./src/Unidays.Tests/
  - cmd: dotnet test
#---- deployment configuration ----#
deploy:
  provider: NuGet
  api_key:
    secure: {NUGET_KEY}
  on:
    branch:
      - master