# master
-
  branches:
    only:
      - master

  image: Visual Studio 2017
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.cs'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
      
  skip_tags: true

  version: 1.0.0
   
  init:
    - git config --global core.autocrlf input

  clone_depth: 1
    
  test_script:
    - cmd: dotnet restore ./src/Unidays.Tests/Unidays.Tests.csproj --verbosity m
    - cmd: cd ./src/Unidays.Tests/
    - cmd: dotnet test

  after_build:
    - ps: nuget pack -version "$($env:appveyor_build_version)"

  artifacts:
    - path: '*.nupkg'

  deploy:
    - provider: NuGet
      api_key:
        secure: $env:nuget_key
      artifact: /.*\.nupkg/
   
  on_failure:
    - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version)-fail-$(Get-Date -format dd_mm_yyyy_HH_mm_ss)"

# everything except master
-
  branches:
    except:
      - master

  image: Visual Studio 2017
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.cs'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

  skip_tags: true

  version: 1.0.0.{build}-{branch}
   
  init:
    - git config --global core.autocrlf input
    
  test_script:
    - cmd: dotnet restore ./src/Unidays.Tests/Unidays.Tests.csproj --verbosity m
    - cmd: cd ./src/Unidays.Tests/
    - cmd: dotnet test

  after_build:
    - ps: nuget pack -version "$($env:appveyor_build_version)"

  artifacts:
    - path: '*.nupkg'
   
  on_failure:
    - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version)-fail-$(Get-Date -format dd_mm_yyyy_HH_mm_ss)"