version: '1.0.{build}'
image: Visual Studio 2017
clone_depth: 1
skip_tags: true
skip_branch_with_pr: true
init:
    - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/Unidays.Client/Unidays.Client.csproj --verbosity m
  - cmd: dotnet restore ./src/Unidays.Client.Tests/Unidays.Client.Tests.csproj --verbosity m   
test_script:    
  - cmd: cd ./src/Unidays.Client.Tests/
  - cmd: dotnet test
on_failure:
    - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version)-fail-$(Get-Date -format dd_mm_yyyy_HH_mm_ss)"
for:
  - branches:
      only:
        - master
    build_script:
      - cmd: dotnet build ./src/Unidays.Client/Unidays.Client.csproj -c Release
      - cmd: dotnet pack ./src/Unidays.Client/Unidays.Client.csproj -c Release /property:PackageVersion=%APPVEYOR_BUILD_VERSION%
    artifacts:
      - path: '**\*.nupkg'
        name: NuGet
  
  - branches:
      except:
        - master
    version: 1.0.{build}-{branch}
