# master
-
  branches:
    only:
      - master

  image: Visual Studio 2017
      
  skip_tags: true

  skip_branch_with_pr: true

  version: 0.1.{build}
   
  init:
    - cmd: git config --global core.autocrlf true

  clone_depth: 1
  
  before_build:
    - cmd: dotnet --version
    - cmd: dotnet restore ./src/Unidays/Unidays.csproj --verbosity m
    - cmd: dotnet restore ./src/Unidays.Tests/Unidays.Tests.csproj --verbosity m

  test_script:
    - cmd: cd ./src/Unidays.Tests/
    - cmd: dotnet test

  build_script:
    - cmd: dotnet build ./src/Unidays/Unidays.csproj -c Release
    - cmd: dotnet pack ./src/Unidays/Unidays.csproj -c Release /property:PackageVersion=0.1.{build}

  after_build:
    - ps: nuget pack -version "$($env:appveyor_build_version)"

  artifacts:
    - path: 'src/Unidays/bin/Release/*.nupkg'
      name: NuGet
  
  deploy:
    - provider: NuGet
      api_key:
        secure: $env:nuget_key
      artifact: /.*\.nupkg/
   
  on_failure:
    - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version)-fail-$(Get-Date -format dd_mm_yyyy_HH_mm_ss)"

# everything except master
-
  branches:
    except:
      - master

  image: Visual Studio 2017

  skip_tags: true

  skip_branch_with_pr: true

  version: 0.1.{build}-{branch}
   
  init:
    - cmd: git config --global core.autocrlf true

  before_build:
    - cmd: dotnet --version
    - cmd: dotnet restore ./src/Unidays/Unidays.csproj --verbosity m
    - cmd: dotnet restore ./src/Unidays.Tests/Unidays.Tests.csproj --verbosity m

  test_script:
    - cmd: cd ./src/Unidays.Tests/
    - cmd: dotnet test

  artifacts:
    - path: '*.nupkg'
   
  on_failure:
    - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version)-fail-$(Get-Date -format dd_mm_yyyy_HH_mm_ss)"